name: JW_LaSEEB_2
dependencies:
  - python=3.7
  - numpy
  - pandas
  - seaborn
  - scikit-learn
  - pip
  - pip:
      - ipympl
      - jupyterlab
      - pydicom
      - SimpleITK
      - itk
      - itkwidgets
      - jupyterlab_code_formatter
      - black
      - isort
